# Generated by Django 3.2.9 on 2021-11-16 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btest', '0002_auto_20211117_0018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rubric',
        ),
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ['-published'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
    ]
