# Generated by Django 3.2.9 on 2021-11-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=15)),
                ('width', models.CharField(max_length=15)),
                ('length', models.CharField(max_length=15)),
                ('weight', models.CharField(max_length=15)),
                ('recdate', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('nofcon', models.FloatField(max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('expdate', models.CharField(max_length=12)),
                ('numofpos', models.FloatField(max_length=10)),
            ],
        ),
    ]
