# Generated by Django 3.2.9 on 2021-11-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr',
            name='nofcon',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pr',
            name='numofpos',
            field=models.CharField(max_length=10),
        ),
    ]
