# Generated by Django 3.2.9 on 2021-11-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whouse', '0002_auto_20211119_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название юр. лица')),
                ('requisites', models.TextField(verbose_name='Банковские реквизиты')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-name'],
            },
        ),
        migrations.AlterModelOptions(
            name='pr',
            options={'ordering': ['-recdate'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='pr',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Указание'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='expdate',
            field=models.CharField(max_length=12, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='height',
            field=models.CharField(max_length=15, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='length',
            field=models.CharField(max_length=15, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='nofcon',
            field=models.CharField(max_length=20, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='numofpos',
            field=models.CharField(max_length=10, verbose_name='Номер позиции'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='recdate',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='weight',
            field=models.CharField(max_length=15, verbose_name='Масса'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='width',
            field=models.CharField(max_length=15, verbose_name='Ширина'),
        ),
    ]
