# Generated by Django 3.2.9 on 2021-11-19 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whouse', '0003_auto_20211119_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='whouse.client', verbose_name='Клиент'),
        ),
    ]
