# Generated by Django 3.2.9 on 2021-11-19 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whouse', '0004_pr_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=20, verbose_name='Номер')),
                ('seats', models.CharField(db_index=True, max_length=20, verbose_name='Количество мест')),
                ('H', models.CharField(db_index=True, max_length=20, verbose_name='Высота места')),
                ('W', models.CharField(db_index=True, max_length=20, verbose_name='ширина места')),
                ('L', models.CharField(db_index=True, max_length=20, verbose_name='Длина места')),
                ('load', models.CharField(db_index=True, max_length=20, verbose_name='Максимальная нагрузка')),
            ],
            options={
                'verbose_name': 'Стеллаж',
                'verbose_name_plural': 'Стеллажи',
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='pr',
            name='rack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='whouse.rack', verbose_name='Стеллаж'),
        ),
    ]
