# Generated by Django 3.2.9 on 2021-11-19 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whouse', '0005_auto_20211119_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namer', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
                ('V', models.CharField(db_index=True, max_length=20, verbose_name='Полезный объем, м^3')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
                'ordering': ['-namer'],
            },
        ),
        migrations.AlterField(
            model_name='pr',
            name='height',
            field=models.CharField(max_length=15, verbose_name='Высота, см'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='length',
            field=models.CharField(max_length=15, verbose_name='Длина, см'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='weight',
            field=models.CharField(max_length=15, verbose_name='Масса, кг'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='width',
            field=models.CharField(max_length=15, verbose_name='Ширина, см'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='H',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Высота места, см'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='L',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Длина места, см'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='W',
            field=models.CharField(db_index=True, max_length=20, verbose_name='ширина места, см'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='load',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Максимальная нагрузка, кг'),
        ),
        migrations.AddField(
            model_name='rack',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='whouse.room', verbose_name='Помещение'),
        ),
    ]
